canonical/awspub

snap/snapcraft.yaml
That way, the snap has a meaningful version for each new revision.
=> fix: use git version for snap

awspub/cli/__init__.py, awspub/image.py, awspub/tests/test_image.py
The new "awspub list ..." command is useful to get a list of available images for the given configuration. The output is similar to the output of "awspub create ..." so this command can be used to get a list of available images.
=> feat: add list command

awspub/configmodels.py, awspub/image.py
The new image configuration option "imds_support" can be set for registering images wit imds support v2.0.
=> feat: add IMDS support

awspub/snapshot.py
When waiting for snapshots in all regions, the waiter can timeout with the current 30 minutes. So increase the timeout.
=> fix: increase wait for snapshot timeout to 45 minutes

awspub/configmodels.py
There was a typo in the configmodels.py so setting the image description didn't work.
=> fix: correctly set description for images

tox.ini
type checking via mypy should be done by default so add the type test to the default tox envlist.
=> test: enable type check during tox run

.github/workflows/automatic-doc-checks.yml, .github/workflows/sphinx-python-dependency-build-checks.yml, conf.py, custom_conf.py, requirements_parser.py, tox.ini
This changes how custom_required_modules is set to pull values directly from poetry.lock. This results in an inflated requirements list, but ensures that future requirements are automatically included.
=> feat: parse sphinx requirements from poetry.lock

custom_conf.py, readme.rst, snap/snapcraft.yaml
not sure if there is something else that needs to be done on the RTD side, but this needs to be done at a minimum
=> fix: move website under canonical readthedocs

awspub/image_marketplace.py, awspub/tests/test_image_marketplace.py
Some characters are valid for a version title, but not the changeset itself. "()" in particular showcased this issue when trying to update images tagged with "(arm)" in the title. This change removes all invalid characters from the version_title before use in the changeset name
=> fix: remove invalid characters from marketplace changeset name

awspub/configmodels.py, awspub/context.py, awspub/tests/fixtures/config-invalid-s3-extra.yaml, awspub/tests/fixtures/config-valid-nonawspub.yaml, awspub/tests/test_context.py
Prev version allowed extra fields while setting configurations. Strict Validation ensures no extra fields/keys shall be passed.
fixes #45
=> fix: added strict validation to not allow  extra fields/keys

awspub/configmodels.py, awspub/exceptions.py, awspub/s3.py, awspub/tests/fixtures/config-invalid-s3-extra.yaml, awspub/tests/fixtures/config-minimal.yaml, awspub/tests/fixtures/config-valid-nonawspub.yaml, awspub/tests/fixtures/config1.yaml, awspub/tests/fixtures/config2.yaml, awspub/tests/fixtures/config3-duplicate-keys.yaml, awspub/tests/test_context.py, awspub/tests/test_image.py, awspub/tests/test_s3.py, docs/config-samples/config-minimal-groups.yaml, docs/config-samples/config-minimal-image-tags.yaml, docs/config-samples/config-minimal-marketplace.yaml, docs/config-samples/config-minimal-public.yaml, docs/config-samples/config-minimal-ssm.yaml, docs/config-samples/config-minimal-tags.yaml, docs/config-samples/config-minimal.yaml, docs/config-samples/config-multiple-images.yaml, docs/config-samples/config-with-parameters.yaml
specifying bucket_region in config makes sharing a single config across aws partitions challenging, and also introduces the possibility of specifying a bucket_name that exists outside of the bucket_region. Instead of requiring users to specify the region, we instead just take the bucket name (which is unique across all regions of a partition) and, if the bucket exists, query aws for the region it is in. If the bucket does not exist, raise an error indicating same.
=> feat: remove bucket_region from config

snap/snapcraft.yaml
Those are the usually used architectures and those 2 architectures are also available on EC2. So only build for those 2.
=> feat(snap): build only for amd64 and arm64

awspub/configmodels.py, awspub/image.py, awspub/tests/test_image.py
If awspub configuration files are used in different partitions than the default (aws) one, it doesn't make sense (and doesn't work) to try to create a Marketplace version update. So make it clear that the marketplace configuration only applies in the default partition. Note: there is also a china marketplace but that's for now not supported.
=> feat: apply marketplace configuration only in default aws partition

pyproject.toml
Instead of hardcoding a version in pyproject.toml, use a poetry plugin to get the version from git. That makes release versioning easier.
=> feat: use version from git

.github/workflows/publish-to-pypi.yaml
With that, it's possible to tag a new release on git and a sdist and whl release will be pushed to pypi.
=> ci: automatically release to test.pypi.org and pypi.org

.github/workflows/publish-to-pypi.yaml
That currently doesn't work because the poetry version plugin does create local versions (see PEP440) but uploading packages with local versions is not allowed.
=> ci: drop automatic publication to test.pypi.org

awspub/snapshot.py
There are sometimes errors while waiting for 30 min for a snapshot to complete. This hopefully helps with:
2024-09-30 23:39:18,921:awspub.snapshot:INFO:Waiting for snap-0d10ebf6308edec1b in ap-south-2 to complete ... Traceback (most recent call last):
File "/snap/awspub/156/bin/awspub", line 8, in <module>
sys.exit(main())
File "/snap/awspub/156/lib/python3.10/site-packages/awspub/cli/__init__.py", line 200, in main
args.func(args)
File "/snap/awspub/156/lib/python3.10/site-packages/awspub/cli/__init__.py", line 66, in _create
image_result: Dict[str, _ImageInfo] = image.create()
File "/snap/awspub/156/lib/python3.10/site-packages/awspub/image.py", line 388, in create
snapshot_ids: Dict[str, str] = self._snapshot.copy(
File "/snap/awspub/156/lib/python3.10/site-packages/awspub/snapshot.py", …
=> feat: wait up to 45 min for snapshot_complete

awspub/image.py
If the marketplace product listed in the configuration is not yet there, the publication step fails and the SSM parameter store update is not executed. So do the SSM parameter store update first to make it more likely that this will be executed.
=> feat: do SSM parameter store update before marketplace

.github/workflows/sphinx-python-dependency-build-checks.yml
This takes care of the `[canonical/awspub] Run failed at startup: Check and document build requirements for Sphinx venv` error that was occurring.
=> ci: correct an error in a GitHub workflow

awspub/image.py
Check for empty list and bail on sharing if no accounts found in partition.
In cases where partition filtering removes all possible accounts from a share list, attempting to share with an empty list will cause a InvalidParameterCombination error to be raised.
=> fix: do not attempt to share image with empty list

custom_conf.py, readme.rst, release-management.rst
That's not useful for end-users so have a separate docs for explaining how to do new releases.
=> docs: move release management into its own docs

awspub/common.py, awspub/configmodels.py, awspub/image.py, awspub/sns.py, awspub/tests/fixtures/config1.yaml, awspub/tests/test_api.py, awspub/tests/test_common.py, awspub/tests/test_image.py, awspub/tests/test_sns.py, docs/config-samples/config-minimal-sns.yaml, docs/how_to/publish.rst
This fix enables the SNS config to specify a
list of regions for sending notifications.
Users can send notifications to specific regions,
but the notification will be sent in every regions if not specified.
=> fix: Allow SNS config has separate list of regions

awspub/exceptions.py, awspub/image.py, awspub/tests/test_image.py
this changes the `awspub create` route to allow images to be distributed to all regions where permission errors do not occur. 
i would like input on if we still want the operation to fail (i.e. ensure a non-zero exit code) or if we want to 'pass with warnings'. if we maintain this implementation then consuming pipelines can pass downstream and perhaps 'release successfully' for all stable regions. this does introduce incomplete sets, but errors could be corrected out of band. current infrastructure won't catch such errors though.
=> feat: allow partial image registration

renovate.json
There's no need to merge those manually if testing passes. So let renovate automerge those.
Refs:
https://docs.renovatebot.com/key-concepts/automerge/#automerge-non-major-updates
=> feat: let renovate automerge minor version bumps

awspub/common.py, awspub/configmodels.py, awspub/image.py, awspub/tests/fixtures/config1.yaml, awspub/tests/test_common.py, awspub/tests/test_image.py, docs/config-samples/config-minimal-share.yaml, docs/how_to/publish.rst
This PR extends "share:" schema to support sharing images with
organizations & organization units by ARN.
Fixes: #105
=> Add support for sharing with Organizations and Organizational Units

awspub/image_marketplace.py, awspub/tests/test_image_marketplace.py
If the marketplace listing doesn't have a version yet, do allow to create a new version request.
This fixes:
File "awspub/image_marketplace.py", line 40, in request_new_version
for version in entity["DetailsDocument"]["Versions"]:
~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'Versions'
=> fix: allow marketplace version update without any existing version
